server:
  port: ${PORT:8080}

spring:
  application:
    name: yedc-academy
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.chfutdrfdodxvjheqrti}
    password: ${SPRING_DATASOURCE_PASSWORD:Bhosale#pa55}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 580000
      keepalive-time: 30000
      validation-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: false
    repair-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:avadhut.build@gmail.com}
    password: ${GMAIL_APP_PASSWORD:fperaqxqhzfieiiw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:rzp_test_mockKeyId}
    secret: ${RAZORPAY_KEY_SECRET:mockKeySecret}
